### ISSUE TITLE
Add passenger counting to realtime apis from Suomenlinna Ferry

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitdata#109]
https://hsl.louhin.com/lati/help

1. OCCU values to HFP/GTFRS-RT
2. Other?

**Comment by samijuhani** [comment]
Pending for api development for now

**Comment by mjaakko** [comment]
We have API for this, e.g. https://hsl-test.louhin.com/lati/departure?date=2020-06-08+06:00:00&stop=0098

**Comment by mjaakko** [comment]
Mostly done https://github.com/HSLdevcom/suomenlinna-ferry-hfp/pull/14, needs testing + waiting for the API to be available in production

**Comment by mjaakko** [comment]
Deployed to prod
