### ISSUE TITLE
Move Google gtfsrt from Digitransit to own host

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitdata#110]
Just to make it so that all services are not dependant of digitransit

**Comment by pierre-leonard** [comment]
This can be done easily by using Azure Functions proxy feature. However, we'll need the ssl certificate in order to support https. Let's wait for Jyrki to come back from vacation

**Comment by pierre-leonard** [comment]
Proxy set up with https://transitdatadevproxy.azurewebsites.net as the server url

**Comment by mjaakko** [comment]
Mostly done, but still waiting for domain name

**Comment by pierre-leonard** [comment]
Domain name set
