### ISSUE TITLE
Use "do not publish" on OMM service alerts

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitdata#111]
New feature on OMM, option to not to publish alerts to API's only to vehicles. Implement usage of this  feature to transitdata.

**Comment by samijuhani** [comment]
Adding exact place where to find this asap

**Comment by samijuhani** [comment]
V43__add_display_only_column_to_passenger_bulletin_meta_data_table.sql

**Comment by samijuhani** [comment]
V43__add_display_only_column_to_passenger_bulletin_meta_data_table.sql

Implement this when possible. Adding new alerts with this option to test environment.

**Comment by samijuhani** [comment]
Bummer, can't add alerts for now as test env is still messed up

**Comment by samijuhani** [comment]
Alerts added after all!

![image](https://user-images.githubusercontent.com/39256978/84742182-cb6d4280-afb8-11ea-9381-f68c63f3dcca.png)

**Comment by mjaakko** [comment]
Should we ignore these alerts completely or only filter them from GTFS RT feeds?

**Comment by samijuhani** [comment]
I'd say filter so we can log that they were there but not published because of the selection?

**Comment by samijuhani** [comment]
This could be implemented as soon as possible as feature is going to prod already tonight with OMM update. We tell users to not use this until our work is finished
