### ISSUE TITLE
Revise partial cancellation source to use only one DB connection (adjust db names in queries accordingly)

### ISSUE THREAD

**Issue by hellej** [HSLdevcom/transitdata#113]
In development two different connections were needed: one for test OMM but it did not have read rights to DOI and thus we used another one for DOI (prod replica). In production only one DB connection should be used (to OMM/DOI replica). 

When making this change, make sure that db names in queries are correct (e.g. `FROM OMM_Community.dbo.affected_departures`)

**Comment by samijuhani** [comment]
Evaluate if this is needed or not before doing

**Comment by mjaakko** [comment]
Database names updated in HSLdevcom/transitdata-stop-cancellation-source#4, still need to change to use only one DB connection
