### ISSUE TITLE
Enhance documentation

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitdata#120]
When nothing urgent ongoing, fallback on these. Mark as done when a part is finished and add new ones if something is missing from the list

https://gitlab.hsl.fi/transitdata/transitdata-notes/-/wikis/home

- [x] Remote debugging guide
- [x] Graylog guide
- [x] Pulsar guide (more example commands)
- [x] Common problem cases and how to solve 
- [ ] Redis guide
- [x] Some basic explanation page of mqtt connections, gtfs, tripupdates etc. maybe?
- [ ] Transitlog related documentation (sink, citus, ...)
- [ ] Why transitdata 2.0 would be ne needed?
- [ ] ...

**Comment by hellej** [comment]
- [x] Remote debugging guide
- [x] Graylog guide
- [x] Pulsar guide (more example commands)
And now I am working on the general troubleshooting, debugging and "fixing transitdata" guide...

Perhaps @Divinare can write something about transitdata 2.0 and @danieldunderfelt about Transitlog?

**Comment by mjaakko** [comment]
Current documentation should be up-to-date
