### ISSUE TITLE
Refactor metro ATS source (5d)

### ISSUE THREAD

**Issue by mjaakko** [HSLdevcom/transitdata#126]
Currently the metro ATS source produces a lot of trip updates due to the way its implemented. This should be changed so that only one trip update is sent when a new estimates are received from metro ATS API.

**Comment by mjaakko** [comment]
rata-digitraffic-source could be helpful when doing this as the data structure is similar

**Comment by pierre-leonard** [comment]
I merged transitdata-metro-ats-parser, transitdata-metro-ats-cancellation and transitdata-stop-estimates. This will reduce the number of messages in transit but there will still be quite a few messages going from the service to transitdata-tripupdate-processor. Is that good enough?

**Comment by mjaakko** [comment]
We also want to simplify the code (currently the cancellation logic is a bit too complex for what is needed) and change the stop estimates logic so that only one trip update is sent when a message from the ATS API is received.

**Comment by pierre-leonard** [comment]
Deployed to dev

**Comment by mjaakko** [comment]
> We also want to simplify the code (currently the cancellation logic is a bit too complex for what is needed) and change the stop estimates logic so that only one trip update is sent when a message from the ATS API is received.

Still would need to do this. Not sure if this is worth the effort.
