### ISSUE TITLE
EKE train tasks (4,5d)

### ISSUE THREAD

**Issue by mjaakko** [HSLdevcom/transitdata#129]
Create a pipeline for storing raw data (train status data) from EKE MQTT API to blob storage

**Comment by pierre-leonard** [comment]
Need more info about the db output format

**Comment by pierre-leonard** [comment]
Write data in csv instead and upload to blob

**Comment by pierre-leonard** [comment]
Pretty much done, waiting to get more data before deploying to prod

**Comment by mjaakko** [comment]
Still need to do:
- [ ] Parse and store balise messages (message format unclear)
- [ ] Think about how to store data (hourly ZIP packages with CSV files as it is now or something else)
  - Should we store parsed data or raw data?
- [ ] Test that the service can handle large amount of messages (#142)
- [ ] Test that everything else works correctly (messages parsed correctly etc.)

**Comment by mjaakko** [comment]
Deployed to prod
