### ISSUE TITLE
Save trip cancellations to CSV dumps

### ISSUE THREAD

**Issue by mjaakko** [HSLdevcom/transitdata#133]
Add support for saving trip cancellations (and cancellations-of-cancellations) to CSV dumps to https://github.com/HSLdevcom/transitlog-cancellation-sink. This will be used by HSL DW to add cancellations to DW. The implementation should be similar to how HFP CSV dumps work.

**Comment by MinnaEmilia** [comment]
This feature is not necessary at this point --> reason for closing the ticket.
