### ISSUE TITLE
Add support for passenger count messages to vehicle position processor

### ISSUE THREAD

**Issue by mjaakko** [HSLdevcom/transitdata#139]
Add support for HFP passenger count messages to vehicleposition-processor so that OccupancyStatus (https://developers.google.com/transit/gtfs-realtime/reference#enum-occupancystatus) can be added to GTFS-RT vehicle position messages. Currently `occu` field from HFP messages is used for this, but only Suomenlinna ferries provide this data. The current implementation could be used as reference on how to map occupancy percentage to GTFS-RT OccupancyStatus enum.

**Comment by pierre-leonard** [comment]
Done, waiting for more data to come in before deploying to prod

**Comment by mjaakko** [comment]
Currently testing in dev

**Comment by mjaakko** [comment]
TODO: Add sanity checks so that invalid data can be ignored (e.g. negative passenger count)

**Comment by mjaakko** [comment]
Deployed to prod for testing with real data. Let's create new issues when new features are needed
