### ISSUE TITLE
TransitData: investigate necessary/unnecessary alerts

### ISSUE THREAD

**Issue by MinnaEmilia** [HSLdevcom/transitdata#151]
tällä tiketillä:
1) Käydään läpi kaikki TransitDatan hälytykset ja tehdään ehdotus, mitkä hälytykset ovat jääneet turhiksi. 
2) kuvataan tarpeelliset hälytykset dokumenttiin käyttäjän näkökulmasta (mitä käyttäjän näkökulmasta tarkoittaa, jos heräte saadaan)
3) Arvioidaan käyttäjäkuvausten perusteella hälytysten kriittisyysluokat. (Minna tekee)

**Comment by teemu8655** [comment]
Closing this one. More spesific isssues will be created later on by need.

**Comment by teemu8655** [comment]
Muutos: Käydään läpi vain kriittiset ja vakavat herätteet ja kuvataa niiden vaikutukset loppukäyttäjälle.

**Comment by teemu8655** [comment]
Closing this one, creating new more detailed separate issues
