### ISSUE TITLE
Improvements for new HFP CSV sink

### ISSUE THREAD

**Issue by mjaakko** [HSLdevcom/transitdata#156]
* [x] Group HFP data to CSV files based on their HFP event type (e.g. `VP`, `ARR` etc.) instead of grouping all related events to same file
* [x] Remove duplicate rows from CSV files
* [ ] ~~Add checksums (MD5) to CSV files that include all fields except `received_at`~~
 * This is probably not needed if duplicate rows are removed
* [x] Add metadata to blobs (at least: row count, min and max tst values, unique values of oday)
 * Tags should work better than metadata for this use case https://docs.microsoft.com/en-us/rest/api/storageservices/find-blobs-by-tags
* [x] Create file names with `received_at` value instead of `tst` (in case messages are delayed or the `tst` value is incorrect)

**Comment by teemu8655** [comment]
Duplicate for #156
