### ISSUE TITLE
Herätteen tutkinta ja elvytystoimet

### ISSUE THREAD

**Issue by teemu8655** [HSLdevcom/transitdata#160]
Transitdatan herätteen "Transitdatan herätettä transitdata/internal-messages/stop-cancellation: MsgRateIn has been 0 for 10 minutes (Daytime alert)" tutkinta ja korjaustoimet

**Comment by karppanenr** [comment]
Tietokantayhteys oli katkennut edeltäneenä iltana, ja järjestelmä ei ollut osannut siitä toipua. Useampi palvelu oli kyykännyt samanaikaisesti illalla, joten ongelma on voinut liittyä alustaan tai ajoympäristöön. Tätä voisi tutkia ainakin miksi ongelmallinen palvelu ei toipunut itse.

**Comment by teemu8655** [comment]
Teen tuosta jatkotyöstä oman tiksun
