### ISSUE TITLE
PubTrans-tietokantayhteyden automaattinen palautuminen virhetilanteissa

### ISSUE THREAD

**Issue by teemu8655** [HSLdevcom/transitdata#161]
28.9.2021 tuli heräte "transitdata/internal-messages/stop-cancellation: MsgRateIn has been 0 for 10 minutes (Daytime alert)". Yhteys PubTransin tietokantaan oli katkennut eikä yhteys toipunut ilman manuaalisia elvytystoimia.

Tutkitaan miksi yhteys ei palautunut ja automatisoidaan yhteyden palautuminen vikatilanteissa. Jos jäännösriskinä on edelleen mahdollinen tilanne, että toimenpiteitä ei saada kaikissa tilanteissa automatisoitua niin sitten ohjeistetaan 24/7 valvontaa palautustoimissa.

DoD: kantayhteyttä yritetään luoda automaattisesti yhteyskatkon jälkeen

**Comment by mjaakko** [comment]
HSLdevcom/transitdata-stop-cancellation-source#16

**Comment by mjaakko** [comment]
Currently testing in dev
