### ISSUE TITLE
EKE sm5connectiontest not working

### ISSUE THREAD

**Issue by teemu8655** [HSLdevcom/transitdata#163]
EKE sm5connectiontest raportoitu toimimattomaksi 4.10.2021. Korjaus asap.

**Comment by karppanenr** [comment]
Transitdata näyttäisi toimivan. Komponentti "EKE-check", joka on se sovellus joka on siis tuo sm2connectiontest ei toimi. Kävi ilmi, että se pyörii itseasissa Transitlogin puolella eikä Transitdatassa. Minulla ei siis ole edes pääsyä sen luokse.

Jaakko ja Anton koittivat ratkoa ongelmaa tänään 5.10. tuloksetta. Transitlogin koneilla on ilmeisesti jokin yhteysongelma, joka ei vielä ratkennut. Eke-checkin siirto Transitdatan puolelle ei myöskään onnistu täysin näppärästi koska se on myös sidottu Transitlogin puolella muihin Azuren resursseihin (esim. App Gateway).

**Comment by mjaakko** [comment]
Seems to be working again. Issues most likely caused by problems in Transitlog dev environment
