### ISSUE TITLE
Matkahuolto GTFS-RT API integration

### ISSUE THREAD

**Issue by teemu8655** [HSLdevcom/transitdata#172]
Integrate to Matkahuolto GTFS-RT API. Ossi will provide endpoint and API keys.

**Comment by teemu8655** [comment]
Split to separate issues if needed

**Comment by teemu8655** [comment]
At least part of public line's 280 busses are providing real time info via that Matkahuolto API

**Comment by mjaakko** [comment]
Static data (GTFS.zip or something) is needed to map Matkahuolto trip IDs to HSL trips

**Comment by mjaakko** [comment]
Static data for line 280 available from: https://finap.fi/#/service/85/76 (GTFS: https://minfoapi.matkahuolto.fi/gtfs/067/gtfs.zip)

**Comment by mjaakko** [comment]
Waiting for access MQTT broker for testing

**Comment by mjaakko** [comment]
> Static data for line 280 available from: https://finap.fi/#/service/85/76 (GTFS: https://minfoapi.matkahuolto.fi/gtfs/067/gtfs.zip)

This GTFS feed might not include data for all trips of route 280, because route 280 has multiple operators

**Comment by mjaakko** [comment]
Testing in dev

**Comment by mjaakko** [comment]
TODO:
* add support for using multiple GTFS feeds, because route 280 has multiple operators
* use distance-based stop matching (stop codes are not included for some stops in the GTFS packages, this is the case at least for Kamppi)

**Comment by teemu8655** [comment]
Matkahuolto operator Joressa ID is 0130

**Comment by mjaakko** [comment]
Deployed to prod
