### ISSUE TITLE
Add passenger counting data to HFP

### ISSUE THREAD

**Issue by teemu8655** [HSLdevcom/transitdata#174]
Add passenger counting data to HFP feed in VP event's occu field. Respect the privacy policy and do not use values under 5%.

To be taken into account:
1. Most of the busses don't send passenger counting data, only less than 100 busses sends data. How to show the difference between no data and real value 0.

**Comment by mjaakko** [comment]
This might be possible to do at the MQTT broker with Node-RED. Think about whether it would make architecturally sense and what consequences it would have

**Comment by teemu8655** [comment]
Closing for now. Not smart to do on Cantrasec side.
