### ISSUE TITLE
Investigate possibility to reduce costs

### ISSUE THREAD

**Issue by jhanninen** [HSLdevcom/transitdata#190]
Azure suggests to reserve instances to save costs.
Let's investigate the following:
1. Check which resources are being used and if they are sized right.
2. Plan the future of the services. Are there some known changes coming, like shutting down or new services?
3. For long-term resources consider whether they could be changes from pay-as-you-go to reserved instances

**Comment by mjaakko** [comment]
Reservations for resources have been made
