### ISSUE TITLE
Create/update azure alerts for 24/7 Transitdata monitoring

### ISSUE THREAD

**Issue by teemu8655** [HSLdevcom/transitdata#199]
Digia Iiris monitoring will end 30.6.2022 and Solita is the new 24/7 Service Center provider. Solita uses only Azure alerts so we need make sure that all necessary alerts are created in Azure for Transitdata services.

**Roadmap:**

Development:
* ~~Slack webhook~~ Template created, monitoring deployed to transitdata-dev
* ~~CPU percentage monitor~~ Template created, monitoring deployed to transitdata-dev
* ~~Available memory monitor~~ Template created, monitoring deployed to transitdata-dev
* Available disk space monitor
* Pulsar topic message count monitor
* Email action group
* ~~Topic stats dev dashboard~~
* ~~VM stats dev dashboard~~
* Monitor whether pulsar services (bookie/broker/zookeper) are alive or not
* Monitor MQTT topic data
* How about: Storage Size query alert && remove storage size alert from transitlog-csv-sink-monitor? There could be multiple alerts with different thresholds: warning, major and critical

Production:
* Deploy all alerts to production
  * We need valid configs (especially which thresholds to use) for this
  * We need to add instructions to each email
* ~~Topic stats prod dashboard~~
* ~~VM stats prod dashboard~~

**Comment by teemu8655** [comment]
Integration url and key for Solita DEV: https://events.pagerduty.com/integration/b600b80d0d314e01d041a690fd9d75dc/enqueue 

All alerts can be sent to Solita DEV env.

**Comment by mjaakko** [comment]
Monitoring in prod
