### ISSUE TITLE
Increase Pulsar OS disk size and change premium SSD to standard SSD

### ISSUE THREAD

**Issue by mjaakko** [HSLdevcom/transitdata#208]
Currently Pulsar OS disks are 30GB, which can get filled up quickly with logs. Change OS disk size to 100GB and change disk type from premium SSD to standard SSD.

**Comment by mjaakko** [comment]
This should be done at the same time as #224 because both of these changes require shutting down Pulsar temporarily

**Comment by mjaakko** [comment]
Let's do this when migrating to AKS. Also consider other options for Pulsar backlogs such as blob storage: https://pulsar.apache.org/docs/2.10.x/tiered-storage-azure/

**Comment by teemu8655** [comment]
Waiting AKS to solve the issue
