### ISSUE TITLE
Issues in metro estimates

### ISSUE THREAD

**Issue by mjaakko** [HSLdevcom/transitdata#215]
* [x] Estimates are before scheduled time
* [ ] Estimates are missing for some stations for some departures

Has a subtask #216

**Comment by teemu8655** [comment]
List for customer feedback:
TBA

**Comment by teemu8655** [comment]
List for other observations:

1. Ghost departures
<img width="364" alt="2 hakis" src="https://user-images.githubusercontent.com/52199408/169243622-1978b890-03ce-47a5-baed-10e3f418c2ac.png">

**Comment by mjaakko** [comment]
![image](https://user-images.githubusercontent.com/32361480/169509656-b42a07da-4615-460b-978d-44d5ae2a4776.png)
Delayed metro causing duplicates (Herttoniemi)
