### ISSUE TITLE
New DR-attribute to HFP messages

### ISSUE THREAD

**Issue by teemu8655** [HSLdevcom/transitdata#245]
HFP VP event loctype field will soon have a new DR attribute.

DR means Dead Reckoning and will be used by VPC when Dead Reckoning mode is active in tunnels or other places under ground like some terminals where GPS is not available.

Describe the dependencies and actions needed before this change.

In December 2022 five Helb busses willl start using this attribute.

![DR attribute](https://user-images.githubusercontent.com/52199408/196644980-86b4630b-9281-49fe-b2f3-939337b414a0.png)

**Comment by mjaakko** [comment]
Actions required:
* [ ] Update transitdata-common
* [ ] Update HFP documentation
* [ ] Check if Transitlog DB needs changes (@ahjyrkia)

**Comment by teemu8655** [comment]
21.11.2022 on suunniteltu ensimmäisten pilottilaitteiden asennus. Asennuksen jälkeen alkaa tulemaan DR-tietoa HFP:ssä.

**Comment by mjaakko** [comment]
Changes deployed to prod
