### ISSUE TITLE
Filter delayed vehicles from GTFS-RT VP feed

### ISSUE THREAD

**Issue by mjaakko** [HSLdevcom/transitdata#258]
Vehicles that are significantly delayed should be filtered by [hsldevcom/transitdata-vehicleposition-processor](https://github.com/hsldevcom/transitdata-vehicleposition-processor) so that they don't get published in GTFS-RT feeds. Vehicles that are significantly delayed (HFP `dl` field) are used for practicing etc i.e. they cannot be boarded by passengers and thus they should be filtered from passenger information.

This should be done by adding a configuration option to vehicleposition-processor for maximum allowed delay and filtering vehicle positions based on that. Default value for maximum delay could be 3 hours

**Comment by mjaakko** [comment]
`dl` field might be unreliable, other option would be using combination of `oday` + `start` and comparing it to the current time

**Comment by LofhJann** [comment]
Deployed to dev for testing
