### ISSUE TITLE
Create matrix documenting which transport modes have vehicle positions and trip update available

### ISSUE THREAD

**Issue by mjaakko** [HSLdevcom/transitdata#259]
* List all transport modes (bus, tram, train, metro, ferry, U-buses, etc.) and whether they have vehicle positions, trip updates and passenger counting available
  * Use color coding: green - data is available, yellow - data is available but with limitations, red - data is not available
* Also specify the source of the data (e.g. LIJ)

**Comment by mjaakko** [comment]
https://dev.azure.com/hslfi/Transitdata/_wiki/wikis/Transitdata%20LTS%20documentation/1631/Available-data-by-Transport-mode#

**Comment by teemu8655** [comment]
Add cancellations to data sources
