### ISSUE TITLE
Test new passenger count data

### ISSUE THREAD

**Issue by mjaakko** [HSLdevcom/transitdata#265]
* [x] 1. Add support for parsing passenger count messages where `oper`, `veh`, `lat`, `long`, `odo`, `jrn`, `line`, `stop`, `vehicleloadratio` (transitdata-common and transitdata-hfp-parser)
* [x] 2. Add instance of this parser to prod environment so that there are two parsers running: one that can parse messages where data is string and one that can parse messages where data is numerical
  * Verify which MQTT broker is used. If different than in prod, we also need to set up second mqtt-pulsar-gateway
* [x] 3. OEM will start sending data in new format from few vehicles
* [x] 4. Verify that Transitdata can parse new messages
* [ ] 5. Report to OEM so that they can deploy change to all vehicles
* [ ] 6. Remove old parser from Transitdata so that only messages with numerical data are parsed

**Comment by mjaakko** [comment]
Changes to prod: https://dev.azure.com/hslfi/Transitdata/_git/transitdata-deploy/pullrequest/6146

**Comment by mjaakko** [comment]
Old parser seems to work for new data format and also the new parser seems to work for old data format except for null values (`"null"` string). Verify what type of null value is used in the new data format and then think about how to continue with this

**Comment by mjaakko** [comment]
Waiting for testing on DW side before new data format can be deployed to all vehicles

**Comment by teemu8655** [comment]
No Transitdata jobs to be done. Closing.
