### ISSUE TITLE
Update vehicle capacities

### ISSUE THREAD

**Issue by teemu8655** [HSLdevcom/transitdata#290]
Update attached vehicle capasities in dev and prod envs.
[20230523 Vehicle capacities.txt](https://github.com/HSLdevcom/transitdata/files/11544301/20230523.Vehicle.capacities.txt)

DEV capacities are listed [here](https://dev.azure.com/hslfi/Transitdata/_git/transitdata-deploy?path=/transitdata-dev.yml&version=GBdev-deploy&_a=contents)

Attached list is an up to date list of APC Telia busses (excluding busses that can use the default value 78).

This is the fastest solution to get parcial APC solution #291 to PROD before a permanent solution #289 is done.

**Comment by mjaakko** [comment]
Config updated for both dev and prod (prod not yet deployed)
