### ISSUE TITLE
Deploy partial APC solution to PROD

### ISSUE THREAD

**Issue by teemu8655** [HSLdevcom/transitdata#291]
Deploy partial APC solution to PROD. It's currently running in DEV and can be deployed to PROD after #290 is done.

Make sure that Transitdata prod receives the partial APC messages from PROD broker and sends the full APC messages to PROD APC broker.

**Comment by mjaakko** [comment]
https://github.com/HSLdevcom/transitdata-apc-protobuf-json-transformer seems to be in a crash loop in prod. Working fine in dev

**Comment by mjaakko** [comment]
> https://github.com/HSLdevcom/transitdata-apc-protobuf-json-transformer seems to be in a crash loop in prod. Working fine in dev

See HSLdevcom/transitdata#292

**Comment by mjaakko** [comment]
Done
