### ISSUE TITLE
Re-enable 24/7 service desk for temporarily disabled alarms

### ISSUE THREAD

**Issue by LofhJann** [HSLdevcom/transitdata#299]
Due to summer time there were some false alarms in dynamic alert system. Re-enable these once enough time has passed for message count to stabilize

- [ ] Revert changes in https://dev.azure.com/hslfi/Azure-automation/_git/azure-infra-pulsar-alerts/pullrequest/8025
- [ ] Approve pipelines for changes to be deployed

**Comment by LofhJann** [comment]
We agreed that date for re-enabling alarms should be 26.6.

**Comment by teemu8655** [comment]
done 27.6.
