### ISSUE TITLE
Create a dev.hsl.fi/gtfs/hsl.zip proxy to redirect GTFS file from Azure to old address for time being

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitdata#48]
GTFS file will be moved from dev.hsl.fi (K5) to https://infopalvelut.storage.hsldev.com/ (Azure) and we want users to be able to fetch the file from the old address still. Create a proxy for the file.

**Comment by samijuhani** [comment]
https://hslstorageinfopalvelut.blob.core.windows.net/$web?restype=container&comp=list

**Comment by mjaakko** [comment]
Latest GTFS file: https://infopalvelut.storage.hsldev.com/gtfs/hsl.zip

**Comment by samijuhani** [comment]
Second part of the ticket: Proxy all other dev.hsl.fi addresses expect gtfs to http://dev.waltti.fi/helsingin-seudun-liikenne/

Use twitter https://twitter.com/HSLdevcom (or post about mainetance) for time being.
