### ISSUE TITLE
Multiply canceled journeys in full dataset because we can not know what trip_id google has

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitdata#50]
See slack for specs.

**Comment by samijuhani** [comment]
Assume google does not have an api for this, that would be too easy then ofc.

**Comment by samijuhani** [comment]
If we create the cancelled ones when it is done, it is needed to add + dates also until that date when cancellation is active, if done beforehand.

**Comment by samijuhani** [comment]
Google gtfs has been changed to daily now so no need to do 7 days anymore, maybe 3.

**Comment by mjaakko** [comment]
Google has confirmed that trip IDs are not required for cancellations.
