### ISSUE TITLE
Mipro ATS API issues

### ISSUE THREAD

**Issue by mjaakko** [HSLdevcom/transitdata#75]
- [ ] Stop time predictions jump ~1 minute backwards and forwards (e.g. 0min -> 1min -> 0min) at least in Vuosaari and Matinkylä
- [ ] Stop time predictions are updated even after the metro has passed the station
- [ ] Predicted arrival time to a station can be before predicted departure time from the previous station
- [x] All metros are cancelled if timetable of the day is changed

- [ ] All metros are cancelled if timetable of the day is changed DURING THE DAY

**Comment by samijuhani** [comment]
- [ ] Case 16.3.: allejäänti Koivusaaren 2-puolen vaihdealueella. Metroa liikennöity OTA-MAK ja LAS-MM/VS 
![image](https://user-images.githubusercontent.com/39256978/80458239-2b405900-8939-11ea-8ac8-59c77581edef.png)

**Comment by samijuhani** [comment]
ATS update is now live. Verify everything works as expected.

**Comment by samijuhani** [comment]
Let's add logging for cancelled journeys and see that there are no more nightly cancellations before enabling cancelled metro journeys.

**Comment by samijuhani** [comment]
Not seeing the desired affect on incorrect prognosis on case number 1

![image](https://user-images.githubusercontent.com/39256978/89767627-01372f00-db03-11ea-8ee8-015d26ae18a8.png)

**Comment by MinnaEmilia** [comment]
This ticket has included testing and following of the problem. Testing will be done once more. If problem cannot be repeated in testing, this ticket will be closed.

**Comment by mjaakko** [comment]
After doing quick testing, it seems that everything is working correctly. Closing this ticket for now, let's create a new one if the problem reappears.
