### ISSUE TITLE
Metro HFP issues

### ISSUE THREAD

**Issue by mjaakko** [HSLdevcom/transitdata#76]
- [ ] Route ID for Mellunmäki-Matinkylä metros should be `31M2M` instead of `31M2` also 3M1B, 3M2B.
- [ ] Some metros register for a trip to the opposite direction before reaching the final station (is this 6)
- [ ] Sometimes multiple metros register for the same trip when the metros are not actually running the same trip
- [ ] Incorrect sending of data at stations (old timestamp with same location, multiple messages)
- [ ] Matinkylä, Mellunmäki is missing first stop data specially in the mornings
- [ ] Sending data too soon while still on a dead run (is this 2)

**Comment by samijuhani** [comment]
#3 
![image](https://user-images.githubusercontent.com/39256978/70995101-5c319700-20d8-11ea-8aa4-f0b426dbe03a.png)

**Comment by samijuhani** [comment]
Juuri nyt
![image](https://user-images.githubusercontent.com/39256978/70996029-9734ca00-20da-11ea-8b1b-508dd405de17.png)

**Comment by samijuhani** [comment]
5
https://reittiloki.hsl.fi/journey/20191205/051000/31M2/2/0050_217?date=2019-12-05&mapView=60.23855690967931%2C25.109730362564733&route.routeId=31M2&route.direction=2&route.originStopId=1473604&tab=vehicle-journeys&details-tab=journey-events&mapZoom=18&live=false&time=05%3A10%3A30&area_search_minutes=20&vehicle=0050%2F217

**Comment by MinnaEmilia** [comment]
This ticket has included testing and following of the problem. Light testing has been done. Problems hasn't been found lately. Therefore this ticket will be closed and opened again if same problem exists again.
