### ISSUE TITLE
Do not produce real time cancellations for Metro if cancellation is made after the journey has passed

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitdata#77]
As in conversation about cases 7-9.12.

**Comment by hellej** [comment]
@samijuhani Is it still ok to make cancellations of cancellations to the past? What about transitlog, do we need to save these for it?

**Comment by samijuhani** [comment]
For real time no cancellation of cancellation is needed as it is not reported to the past at start, does not matter. Transitlog is tricky, we need to see really cancelled journeys but not full days of worth of faulty cancelled. It is not showing those cancellations at this point though so maybe we just leave it to be
