### ISSUE TITLE
Filter out stop estimates from wrong journeys

### ISSUE THREAD

**Issue by hellej** [HSLdevcom/transitdata#90]
If driver logs in to incorrect (earlier or later) journey, the arrival and departure stop time estimates cause unrealistic planned itineraries in route planners.

**Comment by MinnaEmilia** [comment]
Selvitetään onko tämä ongelma edelleen olemassa. Jos on niin tehdään korjaus.

**Comment by MinnaEmilia** [comment]
Problem is not active anymore so let's close the ticket and reopen it again if challenge is noticed later.
