### ISSUE TITLE
Enhance partial cancellation E2E functionality

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitdata#93]
Let's make these work as good as possible with OTP now that we are getting dev-omm access.

1. [Temporarily closed stops #105](https://github.com/HSLdevcom/transitdata/issues/105) (affects all routes and departures that use the stops)
2. [Cancelled stops for specific routes #103](https://github.com/HSLdevcom/transitdata/issues/103) (affects all departures of the affected routes)
3. [Cancelled stops for specific departures #104](https://github.com/HSLdevcom/transitdata/issues/104) (do not affect other routes/departures)
4. [Disruption routes: some stops are replaced with new stops #101](https://github.com/HSLdevcom/transitdata/issues/101) (on hold due to limited support in OTP)

**Comment by mjaakko** [comment]
2. is not supported by GTFS-RT

**Comment by samijuhani** [comment]
Yes, let's think a way to make it work in our case/supported to gtfsrt..

**Comment by hellej** [comment]
From GTFS-RT specs: 

> Trip updates can also provide for more complex scenarios where trips are canceled or added to the schedule, or even re-routed.

**Comment by samijuhani** [comment]
Moved 3. to it's own ticket #101

**Comment by hellej** [comment]
I understood that this is waiting for Contrasec to provide a new MQTT broker for testing the publishing of higher number of messages. This is a blocker for going to production with these. @mjaakko has been preparing the deploy pipeline for prod deploy, so perhaps a merge request could be made from that soon and reviewed together with @pierre-leonard

**Comment by samijuhani** [comment]
Not seeing the request about that, please make sure it is happening/ask them again if we are waiting.

**Comment by samijuhani** [comment]
Request found and eta is today for the broker.

**Comment by samijuhani** [comment]
This is umbrella ticket for stop cancellations enhancements. Close this after all is done.

**Comment by mjaakko** [comment]
Use separate issues for tracking this
