### ISSUE TITLE
Robobus HFP

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitdata#97]
Use https://app.swaggerhub.com/apis-docs/adriashotl/dispatcher-api_for_partners/1.0b#/ to create HFP with ferryhfp prcoessor.

**Comment by samijuhani** [comment]
Jaakko to check if data is flowing already as bus is operating. I have asked operator about this also but no answer yet on the status of api.

FYI: agreed to not go to prod with this before passengers are allowed inside but we should do it ready for that.

**Comment by samijuhani** [comment]
Waiting for API key and confirmation that data is there to use.

**Comment by mjaakko** [comment]
Currently in prod: https://reittiopas.hsl.fi/linjat/HSL:1029R/pysakit/HSL:1029R:0:01
