### ISSUE TITLE
Create API for HFP in DW

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitdata#99]
Create an API for anyone to fetch HFP data from DW (#98).  Need to have date and time selection, message type. Be sure to check it will not be extremely expensive for us and maybe we need to limit the maximum amount of data to be fetched at once?

Consider adding fetching of private data also. Maybe use Reittiloki credentials for those?

**Comment by samijuhani** [comment]
Should there be route, direction, vehicle selection/filter also..

**Comment by samijuhani** [comment]
Discussed with Teemu H. and specs for API MVP should be:

- Date (and time?) from and to (calendar)
- Line (added this myself)
- Route
- Direction
- Vehicle (operator and side number)
- Stop (added this myself)
- Event type selection
- [ ] VP
- [ ] Event

**Comment by samijuhani** [comment]
Scope reduced for now to just share the data from blob and compine as daily packets. Also todo before releasing:

- [ ] Move UnsignedEvent-types to private folder

**Comment by samijuhani** [comment]
This can be continued during summer when other things are slower

**Comment by samijuhani** [comment]
Investigate if this can be done or should we change plans.

**Comment by mjaakko** [comment]
Did some rough benchmarking with this and it seems that it is not possible to create an efficient API for this simply due to the amount of data. Downloading the data, processing it and uploading the result would take roughly 30 minutes per one day's worth of data.

**Comment by MinnaEmilia** [comment]
Need for this feature will be discussed after summer holidays.

**Comment by MinnaEmilia** [comment]
decided that this feature is not needed in transitdata --> closing ticket.
